### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by hg**
- styles are future-proof and clearly divided
- everything is indented with 2 spaces
- there's a style guide, albeit basic
- a lot of unnecessary styles have been removed
- some other fixes

### CODE REVIEW

**Comment by hg** [comment]
cc @talc

**Comment by Inumedia** [comment]
Why two spaces, why not 4?

**Comment by hg** [comment]
@Inumedia it's the standard for html, css and js. plus github renders it nicely

**Comment by Inumedia** [comment]
Do you have a source for it being a standard? Aside from github making it render nicely?

**Comment by hg** [comment]
@Inumedia 
GitHub: http://primercss.io/guidelines/#general-formatting
Google: https://google.github.io/styleguide/htmlcssguide.xml?showone=Indentation#Indentation
Mozilla: https://github.com/mozilla/pdf.js/wiki/Style-Guide#general

pretty much any large company/everyone

**Comment by hg** [comment]
@talc HELLO

**Pull request merged**
